void *
GetAddressByName
(const char *name)
{
	if (NULL == name) return NULL;
	else if (0 == strcmp(name, "CreateMappedBitmap")) return (void *)CreateMappedBitmap;
//	else if (0 == strcmp(name, "CreatePropertySheetPage")) return (void *)CreatePropertySheetPage;
	else if (0 == strcmp(name, "CreatePropertySheetPageA")) return (void *)CreatePropertySheetPageA;
	else if (0 == strcmp(name, "CreatePropertySheetPageW")) return (void *)CreatePropertySheetPageW;
//	else if (0 == strcmp(name, "CreateStatusWindow")) return (void *)CreateStatusWindow;
	else if (0 == strcmp(name, "CreateStatusWindowA")) return (void *)CreateStatusWindowA;
	else if (0 == strcmp(name, "CreateStatusWindowW")) return (void *)CreateStatusWindowW;
//	else if (0 == strcmp(name, "CreateToolbar")) return (void *)CreateToolbar;
	else if (0 == strcmp(name, "CreateToolbarEx")) return (void *)CreateToolbarEx;
	else if (0 == strcmp(name, "CreateUpDownControl")) return (void *)CreateUpDownControl;
	else if (0 == strcmp(name, "DestroyPropertySheetPage")) return (void *)DestroyPropertySheetPage;
//	else if (0 == strcmp(name, "DllGetVersion")) return (void *)DllGetVersion;
	else if (0 == strcmp(name, "DllInstall")) return (void *)DllInstall;
	else if (0 == strcmp(name, "DrawInsert")) return (void *)DrawInsert;
//	else if (0 == strcmp(name, "DrawStatusText")) return (void *)DrawStatusText;
	else if (0 == strcmp(name, "DrawStatusTextA")) return (void *)DrawStatusTextA;
	else if (0 == strcmp(name, "DrawStatusTextW")) return (void *)DrawStatusTextW;
	else if (0 == strcmp(name, "FlatSB_EnableScrollBar")) return (void *)FlatSB_EnableScrollBar;
	else if (0 == strcmp(name, "FlatSB_GetScrollInfo")) return (void *)FlatSB_GetScrollInfo;
	else if (0 == strcmp(name, "FlatSB_GetScrollPos")) return (void *)FlatSB_GetScrollPos;
	else if (0 == strcmp(name, "FlatSB_GetScrollProp")) return (void *)FlatSB_GetScrollProp;
	else if (0 == strcmp(name, "FlatSB_GetScrollRange")) return (void *)FlatSB_GetScrollRange;
	else if (0 == strcmp(name, "FlatSB_SetScrollInfo")) return (void *)FlatSB_SetScrollInfo;
	else if (0 == strcmp(name, "FlatSB_SetScrollPos")) return (void *)FlatSB_SetScrollPos;
	else if (0 == strcmp(name, "FlatSB_SetScrollProp")) return (void *)FlatSB_SetScrollProp;
	else if (0 == strcmp(name, "FlatSB_SetScrollRange")) return (void *)FlatSB_SetScrollRange;
	else if (0 == strcmp(name, "FlatSB_ShowScrollBar")) return (void *)FlatSB_ShowScrollBar;
	else if (0 == strcmp(name, "GetEffectiveClientRect")) return (void *)GetEffectiveClientRect;
//	else if (0 == strcmp(name, "GetMUILanguage")) return (void *)GetMUILanguage;
	else if (0 == strcmp(name, "ImageList_Add")) return (void *)ImageList_Add;
	else if (0 == strcmp(name, "ImageList_AddIcon")) return (void *)ImageList_AddIcon;
	else if (0 == strcmp(name, "ImageList_AddMasked")) return (void *)ImageList_AddMasked;
	else if (0 == strcmp(name, "ImageList_BeginDrag")) return (void *)ImageList_BeginDrag;
	else if (0 == strcmp(name, "ImageList_Copy")) return (void *)ImageList_Copy;
	else if (0 == strcmp(name, "ImageList_Create")) return (void *)ImageList_Create;
	else if (0 == strcmp(name, "ImageList_Destroy")) return (void *)ImageList_Destroy;
	else if (0 == strcmp(name, "ImageList_DragEnter")) return (void *)ImageList_DragEnter;
	else if (0 == strcmp(name, "ImageList_DragLeave")) return (void *)ImageList_DragLeave;
	else if (0 == strcmp(name, "ImageList_DragMove")) return (void *)ImageList_DragMove;
	else if (0 == strcmp(name, "ImageList_DragShowNolock")) return (void *)ImageList_DragShowNolock;
	else if (0 == strcmp(name, "ImageList_Draw")) return (void *)ImageList_Draw;
	else if (0 == strcmp(name, "ImageList_DrawEx")) return (void *)ImageList_DrawEx;
	else if (0 == strcmp(name, "ImageList_DrawIndirect")) return (void *)ImageList_DrawIndirect;
	else if (0 == strcmp(name, "ImageList_Duplicate")) return (void *)ImageList_Duplicate;
	else if (0 == strcmp(name, "ImageList_EndDrag")) return (void *)ImageList_EndDrag;
	else if (0 == strcmp(name, "ImageList_GetBkColor")) return (void *)ImageList_GetBkColor;
	else if (0 == strcmp(name, "ImageList_GetDragImage")) return (void *)ImageList_GetDragImage;
//	else if (0 == strcmp(name, "ImageList_GetFlags")) return (void *)ImageList_GetFlags;
	else if (0 == strcmp(name, "ImageList_GetIcon")) return (void *)ImageList_GetIcon;
	else if (0 == strcmp(name, "ImageList_GetIconSize")) return (void *)ImageList_GetIconSize;
	else if (0 == strcmp(name, "ImageList_GetImageCount")) return (void *)ImageList_GetImageCount;
	else if (0 == strcmp(name, "ImageList_GetImageInfo")) return (void *)ImageList_GetImageInfo;
//	else if (0 == strcmp(name, "ImageList_GetImageRect")) return (void *)ImageList_GetImageRect;
//	else if (0 == strcmp(name, "ImageList_LoadImage")) return (void *)ImageList_LoadImage;
	else if (0 == strcmp(name, "ImageList_LoadImageA")) return (void *)ImageList_LoadImageA;
	else if (0 == strcmp(name, "ImageList_LoadImageW")) return (void *)ImageList_LoadImageW;
	else if (0 == strcmp(name, "ImageList_Merge")) return (void *)ImageList_Merge;
	else if (0 == strcmp(name, "ImageList_Read")) return (void *)ImageList_Read;
	else if (0 == strcmp(name, "ImageList_Remove")) return (void *)ImageList_Remove;
//	else if (0 == strcmp(name, "ImageList_Replace")) return (void *)ImageList_Replace;
	else if (0 == strcmp(name, "ImageList_ReplaceIcon")) return (void *)ImageList_ReplaceIcon;
	else if (0 == strcmp(name, "ImageList_SetBkColor")) return (void *)ImageList_SetBkColor;
	else if (0 == strcmp(name, "ImageList_SetDragCursorImage")) return (void *)ImageList_SetDragCursorImage;
//	else if (0 == strcmp(name, "ImageList_SetFilter")) return (void *)ImageList_SetFilter;
//	else if (0 == strcmp(name, "ImageList_SetFlags")) return (void *)ImageList_SetFlags;
	else if (0 == strcmp(name, "ImageList_SetIconSize")) return (void *)ImageList_SetIconSize;
	else if (0 == strcmp(name, "ImageList_SetImageCount")) return (void *)ImageList_SetImageCount;
	else if (0 == strcmp(name, "ImageList_SetOverlayImage")) return (void *)ImageList_SetOverlayImage;
	else if (0 == strcmp(name, "ImageList_Write")) return (void *)ImageList_Write;
	else if (0 == strcmp(name, "InitCommonControls")) return (void *)InitCommonControls;
	else if (0 == strcmp(name, "InitCommonControlsEx")) return (void *)InitCommonControlsEx;
//	else if (0 == strcmp(name, "InitMUILanguage")) return (void *)InitMUILanguage;
	else if (0 == strcmp(name, "InitializeFlatSB")) return (void *)InitializeFlatSB;
	else if (0 == strcmp(name, "LBItemFromPt")) return (void *)LBItemFromPt;
	else if (0 == strcmp(name, "MakeDragList")) return (void *)MakeDragList;
	else if (0 == strcmp(name, "MenuHelp")) return (void *)MenuHelp;
//	else if (0 == strcmp(name, "PropertySheet")) return (void *)PropertySheet;
	else if (0 == strcmp(name, "PropertySheetA")) return (void *)PropertySheetA;
	else if (0 == strcmp(name, "PropertySheetW")) return (void *)PropertySheetW;
	else if (0 == strcmp(name, "ShowHideMenuCtl")) return (void *)ShowHideMenuCtl;
	else if (0 == strcmp(name, "UninitializeFlatSB")) return (void *)UninitializeFlatSB;
//	else if (0 == strcmp(name, "_TrackMouseEvent")) return (void *)_TrackMouseEvent;
	return NULL;
}
