void *
GetAddressByOrder
(int order)
{
	switch (order) {
	case 8:		return (void*)CreateMappedBitmap;
//	case 12:	return (void*)CreatePropertySheetPage;
	case 18:	return (void*)CreatePropertySheetPageA;
	case 19:	return (void*)CreatePropertySheetPageW;
//	case 20:	return (void*)CreateStatusWindow;
	case 6:		return (void*)CreateStatusWindowA;
	case 21:	return (void*)CreateStatusWindowW;
//	case 7:		return (void*)CreateToolbar;
	case 22:	return (void*)CreateToolbarEx;
	case 16:	return (void*)CreateUpDownControl;
	case 23:	return (void*)DestroyPropertySheetPage;
//	case 24:	return (void*)DllGetVersion;
	case 25:	return (void*)DllInstall;
	case 15:	return (void*)DrawInsert;
//	case 26:	return (void*)DrawStatusText;
	case 5:		return (void*)DrawStatusTextA;
	case 27:	return (void*)DrawStatusTextW;
	case 28:	return (void*)FlatSB_EnableScrollBar;
	case 29:	return (void*)FlatSB_GetScrollInfo;
	case 30:	return (void*)FlatSB_GetScrollPos;
	case 31:	return (void*)FlatSB_GetScrollProp;
	case 32:	return (void*)FlatSB_GetScrollRange;
	case 33:	return (void*)FlatSB_SetScrollInfo;
	case 34:	return (void*)FlatSB_SetScrollPos;
	case 35:	return (void*)FlatSB_SetScrollProp;
	case 36:	return (void*)FlatSB_SetScrollRange;
	case 37:	return (void*)FlatSB_ShowScrollBar;
	case 4:		return (void*)GetEffectiveClientRect;
//	case 38:	return (void*)GetMUILanguage;
	case 39:	return (void*)ImageList_Add;
	case 40:	return (void*)ImageList_AddIcon;
	case 41:	return (void*)ImageList_AddMasked;
	case 42:	return (void*)ImageList_BeginDrag;
	case 43:	return (void*)ImageList_Copy;
	case 44:	return (void*)ImageList_Create;
	case 45:	return (void*)ImageList_Destroy;
	case 46:	return (void*)ImageList_DragEnter;
	case 47:	return (void*)ImageList_DragLeave;
	case 48:	return (void*)ImageList_DragMove;
	case 49:	return (void*)ImageList_DragShowNolock;
	case 50:	return (void*)ImageList_Draw;
	case 51:	return (void*)ImageList_DrawEx;
	case 52:	return (void*)ImageList_DrawIndirect;
	case 53:	return (void*)ImageList_Duplicate;
	case 54:	return (void*)ImageList_EndDrag;
	case 55:	return (void*)ImageList_GetBkColor;
	case 56:	return (void*)ImageList_GetDragImage;
//	case 57:	return (void*)ImageList_GetFlags;
	case 58:	return (void*)ImageList_GetIcon;
	case 59:	return (void*)ImageList_GetIconSize;
	case 60:	return (void*)ImageList_GetImageCount;
	case 61:	return (void*)ImageList_GetImageInfo;
//	case 62:	return (void*)ImageList_GetImageRect;
//	case 63:	return (void*)ImageList_LoadImage;
	case 64:	return (void*)ImageList_LoadImageA;
	case 65:	return (void*)ImageList_LoadImageW;
	case 66:	return (void*)ImageList_Merge;
	case 67:	return (void*)ImageList_Read;
	case 68:	return (void*)ImageList_Remove;
//	case 69:	return (void*)ImageList_Replace;
	case 70:	return (void*)ImageList_ReplaceIcon;
	case 75:	return (void*)ImageList_SetBkColor;
	case 76:	return (void*)ImageList_SetDragCursorImage;
//	case 77:	return (void*)ImageList_SetFilter;
//	case 78:	return (void*)ImageList_SetFlags;
	case 79:	return (void*)ImageList_SetIconSize;
	case 80:	return (void*)ImageList_SetImageCount;
	case 81:	return (void*)ImageList_SetOverlayImage;
	case 82:	return (void*)ImageList_Write;
	case 17:	return (void*)InitCommonControls;
	case 83:	return (void*)InitCommonControlsEx;
//	case 84:	return (void*)InitMUILanguage;
	case 85:	return (void*)InitializeFlatSB;
	case 14:	return (void*)LBItemFromPt;
	case 13:	return (void*)MakeDragList;
	case 2:		return (void*)MenuHelp;
//	case 86:	return (void*)PropertySheet;
	case 87:	return (void*)PropertySheetA;
	case 88:	return (void*)PropertySheetW;
	case 3:		return (void*)ShowHideMenuCtl;
	case 89:	return (void*)UninitializeFlatSB;
//	case 90:	return (void*)_TrackMouseEvent;
	}
	return NULL;
}
