void *
GetAddressByName
(const char *name)
{
	if (NULL == name) return NULL;
//	else if (0 == strcmp(name, "ImmActivateLayout")) return (void *)ImmActivateLayout;
	else if (0 == strcmp(name, "ImmAssociateContext")) return (void *)ImmAssociateContext;
	else if (0 == strcmp(name, "ImmAssociateContextEx")) return (void *)ImmAssociateContextEx;
//	else if (0 == strcmp(name, "ImmCallImeConsoleIME")) return (void *)ImmCallImeConsoleIME;
	else if (0 == strcmp(name, "ImmConfigureIMEA")) return (void *)ImmConfigureIMEA;
	else if (0 == strcmp(name, "ImmConfigureIMEW")) return (void *)ImmConfigureIMEW;
	else if (0 == strcmp(name, "ImmCreateContext")) return (void *)ImmCreateContext;
//	else if (0 == strcmp(name, "ImmCreateIMCC")) return (void *)ImmCreateIMCC;
//	else if (0 == strcmp(name, "ImmCreateSoftKeyboard")) return (void *)ImmCreateSoftKeyboard;
	else if (0 == strcmp(name, "ImmDestroyContext")) return (void *)ImmDestroyContext;
//	else if (0 == strcmp(name, "ImmDestroyIMCC")) return (void *)ImmDestroyIMCC;
//	else if (0 == strcmp(name, "ImmDestroySoftKeyboard")) return (void *)ImmDestroySoftKeyboard;
	else if (0 == strcmp(name, "ImmDisableIME")) return (void *)ImmDisableIME;
//	else if (0 == strcmp(name, "ImmDisableIme")) return (void *)ImmDisableIme;
//	else if (0 == strcmp(name, "ImmEnumInputContext")) return (void *)ImmEnumInputContext;
	else if (0 == strcmp(name, "ImmEnumRegisterWordA")) return (void *)ImmEnumRegisterWordA;
	else if (0 == strcmp(name, "ImmEnumRegisterWordW")) return (void *)ImmEnumRegisterWordW;
	else if (0 == strcmp(name, "ImmEscapeA")) return (void *)ImmEscapeA;
	else if (0 == strcmp(name, "ImmEscapeW")) return (void *)ImmEscapeW;
//	else if (0 == strcmp(name, "ImmFreeLayout")) return (void *)ImmFreeLayout;
//	else if (0 == strcmp(name, "ImmGenerateMessage")) return (void *)ImmGenerateMessage;
	else if (0 == strcmp(name, "ImmGetCandidateListA")) return (void *)ImmGetCandidateListA;
	else if (0 == strcmp(name, "ImmGetCandidateListCountA")) return (void *)ImmGetCandidateListCountA;
	else if (0 == strcmp(name, "ImmGetCandidateListCountW")) return (void *)ImmGetCandidateListCountW;
	else if (0 == strcmp(name, "ImmGetCandidateListW")) return (void *)ImmGetCandidateListW;
	else if (0 == strcmp(name, "ImmGetCandidateWindow")) return (void *)ImmGetCandidateWindow;
	else if (0 == strcmp(name, "ImmGetCompositionFontA")) return (void *)ImmGetCompositionFontA;
	else if (0 == strcmp(name, "ImmGetCompositionFontW")) return (void *)ImmGetCompositionFontW;
	else if (0 == strcmp(name, "ImmGetCompositionStringA")) return (void *)ImmGetCompositionStringA;
	else if (0 == strcmp(name, "ImmGetCompositionStringW")) return (void *)ImmGetCompositionStringW;
	else if (0 == strcmp(name, "ImmGetCompositionWindow")) return (void *)ImmGetCompositionWindow;
	else if (0 == strcmp(name, "ImmGetContext")) return (void *)ImmGetContext;
	else if (0 == strcmp(name, "ImmGetConversionListA")) return (void *)ImmGetConversionListA;
	else if (0 == strcmp(name, "ImmGetConversionListW")) return (void *)ImmGetConversionListW;
	else if (0 == strcmp(name, "ImmGetConversionStatus")) return (void *)ImmGetConversionStatus;
	else if (0 == strcmp(name, "ImmGetDefaultIMEWnd")) return (void *)ImmGetDefaultIMEWnd;
	else if (0 == strcmp(name, "ImmGetDescriptionA")) return (void *)ImmGetDescriptionA;
	else if (0 == strcmp(name, "ImmGetDescriptionW")) return (void *)ImmGetDescriptionW;
	else if (0 == strcmp(name, "ImmGetGuideLineA")) return (void *)ImmGetGuideLineA;
	else if (0 == strcmp(name, "ImmGetGuideLineW")) return (void *)ImmGetGuideLineW;
//	else if (0 == strcmp(name, "ImmGetHotKey")) return (void *)ImmGetHotKey;
//	else if (0 == strcmp(name, "ImmGetIMCCLockCount")) return (void *)ImmGetIMCCLockCount;
//	else if (0 == strcmp(name, "ImmGetIMCCSize")) return (void *)ImmGetIMCCSize;
//	else if (0 == strcmp(name, "ImmGetIMCLockCount")) return (void *)ImmGetIMCLockCount;
	else if (0 == strcmp(name, "ImmGetIMEFileNameA")) return (void *)ImmGetIMEFileNameA;
	else if (0 == strcmp(name, "ImmGetIMEFileNameW")) return (void *)ImmGetIMEFileNameW;
//	else if (0 == strcmp(name, "ImmGetImeInfoEx")) return (void *)ImmGetImeInfoEx;
	else if (0 == strcmp(name, "ImmGetImeMenuItemsA")) return (void *)ImmGetImeMenuItemsA;
	else if (0 == strcmp(name, "ImmGetImeMenuItemsW")) return (void *)ImmGetImeMenuItemsW;
	else if (0 == strcmp(name, "ImmGetOpenStatus")) return (void *)ImmGetOpenStatus;
	else if (0 == strcmp(name, "ImmGetProperty")) return (void *)ImmGetProperty;
	else if (0 == strcmp(name, "ImmGetRegisterWordStyleA")) return (void *)ImmGetRegisterWordStyleA;
	else if (0 == strcmp(name, "ImmGetRegisterWordStyleW")) return (void *)ImmGetRegisterWordStyleW;
	else if (0 == strcmp(name, "ImmGetStatusWindowPos")) return (void *)ImmGetStatusWindowPos;
	else if (0 == strcmp(name, "ImmGetVirtualKey")) return (void *)ImmGetVirtualKey;
//	else if (0 == strcmp(name, "ImmIMPGetIMEA")) return (void *)ImmIMPGetIMEA;
//	else if (0 == strcmp(name, "ImmIMPGetIMEW")) return (void *)ImmIMPGetIMEW;
//	else if (0 == strcmp(name, "ImmIMPQueryIMEA")) return (void *)ImmIMPQueryIMEA;
//	else if (0 == strcmp(name, "ImmIMPQueryIMEW")) return (void *)ImmIMPQueryIMEW;
//	else if (0 == strcmp(name, "ImmIMPSetIMEA")) return (void *)ImmIMPSetIMEA;
//	else if (0 == strcmp(name, "ImmIMPSetIMEW")) return (void *)ImmIMPSetIMEW;
	else if (0 == strcmp(name, "ImmInstallIMEA")) return (void *)ImmInstallIMEA;
	else if (0 == strcmp(name, "ImmInstallIMEW")) return (void *)ImmInstallIMEW;
	else if (0 == strcmp(name, "ImmIsIME")) return (void *)ImmIsIME;
	else if (0 == strcmp(name, "ImmIsUIMessageA")) return (void *)ImmIsUIMessageA;
	else if (0 == strcmp(name, "ImmIsUIMessageW")) return (void *)ImmIsUIMessageW;
//	else if (0 == strcmp(name, "ImmLoadIME")) return (void *)ImmLoadIME;
//	else if (0 == strcmp(name, "ImmLoadLayout")) return (void *)ImmLoadLayout;
//	else if (0 == strcmp(name, "ImmLockClientImc")) return (void *)ImmLockClientImc;
//	else if (0 == strcmp(name, "ImmLockIMC")) return (void *)ImmLockIMC;
//	else if (0 == strcmp(name, "ImmLockIMCC")) return (void *)ImmLockIMCC;
//	else if (0 == strcmp(name, "ImmLockImeDpi")) return (void *)ImmLockImeDpi;
	else if (0 == strcmp(name, "ImmNotifyIME")) return (void *)ImmNotifyIME;
//	else if (0 == strcmp(name, "ImmPenAuxInput")) return (void *)ImmPenAuxInput;
//	else if (0 == strcmp(name, "ImmProcessKey")) return (void *)ImmProcessKey;
//	else if (0 == strcmp(name, "ImmPutImeMenuItemsIntoMappedFile")) return (void *)ImmPutImeMenuItemsIntoMappedFile;
//	else if (0 == strcmp(name, "ImmReSizeIMCC")) return (void *)ImmReSizeIMCC;
//	else if (0 == strcmp(name, "ImmRegisterClient")) return (void *)ImmRegisterClient;
	else if (0 == strcmp(name, "ImmRegisterWordA")) return (void *)ImmRegisterWordA;
	else if (0 == strcmp(name, "ImmRegisterWordW")) return (void *)ImmRegisterWordW;
	else if (0 == strcmp(name, "ImmReleaseContext")) return (void *)ImmReleaseContext;
//	else if (0 == strcmp(name, "ImmRequestMessageA")) return (void *)ImmRequestMessageA;
//	else if (0 == strcmp(name, "ImmRequestMessageW")) return (void *)ImmRequestMessageW;
//	else if (0 == strcmp(name, "ImmSendIMEMessageExA")) return (void *)ImmSendIMEMessageExA;
//	else if (0 == strcmp(name, "ImmSendIMEMessageExW")) return (void *)ImmSendIMEMessageExW;
//	else if (0 == strcmp(name, "ImmSendMessageToActiveDefImeWndW")) return (void *)ImmSendMessageToActiveDefImeWndW;
//	else if (0 == strcmp(name, "ImmSetActiveContext")) return (void *)ImmSetActiveContext;
//	else if (0 == strcmp(name, "ImmSetActiveContextConsoleIME")) return (void *)ImmSetActiveContextConsoleIME;
	else if (0 == strcmp(name, "ImmSetCandidateWindow")) return (void *)ImmSetCandidateWindow;
	else if (0 == strcmp(name, "ImmSetCompositionFontA")) return (void *)ImmSetCompositionFontA;
	else if (0 == strcmp(name, "ImmSetCompositionFontW")) return (void *)ImmSetCompositionFontW;
	else if (0 == strcmp(name, "ImmSetCompositionStringA")) return (void *)ImmSetCompositionStringA;
	else if (0 == strcmp(name, "ImmSetCompositionStringW")) return (void *)ImmSetCompositionStringW;
	else if (0 == strcmp(name, "ImmSetCompositionWindow")) return (void *)ImmSetCompositionWindow;
	else if (0 == strcmp(name, "ImmSetConversionStatus")) return (void *)ImmSetConversionStatus;
//	else if (0 == strcmp(name, "ImmSetHotKey")) return (void *)ImmSetHotKey;
	else if (0 == strcmp(name, "ImmSetOpenStatus")) return (void *)ImmSetOpenStatus;
	else if (0 == strcmp(name, "ImmSetStatusWindowPos")) return (void *)ImmSetStatusWindowPos;
//	else if (0 == strcmp(name, "ImmShowSoftKeyboard")) return (void *)ImmShowSoftKeyboard;
	else if (0 == strcmp(name, "ImmSimulateHotKey")) return (void *)ImmSimulateHotKey;
//	else if (0 == strcmp(name, "ImmSystemHandler")) return (void *)ImmSystemHandler;
//	else if (0 == strcmp(name, "ImmTranslateMessage")) return (void *)ImmTranslateMessage;
//	else if (0 == strcmp(name, "ImmUnlockClientImc")) return (void *)ImmUnlockClientImc;
//	else if (0 == strcmp(name, "ImmUnlockIMC")) return (void *)ImmUnlockIMC;
//	else if (0 == strcmp(name, "ImmUnlockIMCC")) return (void *)ImmUnlockIMCC;
//	else if (0 == strcmp(name, "ImmUnlockImeDpi")) return (void *)ImmUnlockImeDpi;
	else if (0 == strcmp(name, "ImmUnregisterWordA")) return (void *)ImmUnregisterWordA;
	else if (0 == strcmp(name, "ImmUnregisterWordW")) return (void *)ImmUnregisterWordW;
//	else if (0 == strcmp(name, "ImmWINNLSEnableIME")) return (void *)ImmWINNLSEnableIME;
//	else if (0 == strcmp(name, "ImmWINNLSGetEnableStatus")) return (void *)ImmWINNLSGetEnableStatus;
//	else if (0 == strcmp(name, "ImmWINNLSGetIMEHotkey")) return (void *)ImmWINNLSGetIMEHotkey;
	return NULL;
}
